### ISSUE TITLE
opacity | filter

### ISSUE THREAD

**Issue by yongheng2016** [yongheng2016/IE-Hack#1]
### 兼容情况：
+ opacity: 
支持IE9+
[http://caniuse.com/#search=opacity](http://caniuse.com/#search=opacity)
+ filter: [http://caniuse.com/#search=filter](http://caniuse.com/#search=filter)
## Demo1:
```css
1 .opacity{
2  filter:alpha(opacity=50);       /* IE */
3  -moz-opacity:0.5;              /* 老版Mozilla */
4  -khtml-opacity:0.5;              /* 老版Safari */
5  opacity: 0.5;           /* 支持opacity的浏览器*/
6 }
```
参考： [http://www.cnblogs.com/netwenchao/archive/2009/07/16/1525077.html](http://www.cnblogs.com/netwenchao/archive/2009/07/16/1525077.html)
### Demo2:
```css
.transparent_class {  
    /* Required for IE 5, 6, 7 */  
    /* ...or something to trigger hasLayout, like zoom: 1; */  
    width:300px;  
    height:300px;  
    line-height:300px;  
    text-align:center;  
    background:#000;  
    color:#fff;  
    /* older safari/Chrome browsers */  
    -webkit-opacity: 0.5;  
    /* Netscape and Older than Firefox 0.9 */  
    -moz-opacity: 0.5;  
    /* Safari 1.x (pre WebKit!) 老式khtml内核的Safari浏览器*/  
    -khtml-opacity: 0.5;  
    /* IE9 + etc...modern browsers */  
    opacity: .5;  
    /* IE 4-9 */  
    filter:alpha(opacity=50);  
    /*This works in IE 8 & 9 too*/  
    -ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=50)";  
    /*IE4-IE9*/  
    filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=50);  
}  
```
代码：[http://js.jirengu.com/locugogexa/1/edit?html,css,output](http://js.jirengu.com/locugogexa/1/edit?html,css,output)

参考：   [http://blog.csdn.net/freshlover/article/details/17143341](http://blog.csdn.net/freshlover/article/details/17143341)
